### ISSUE TITLE
demande de contact! 

### ISSUE THREAD

**Issue by Simon-Syd** [virtazp/WP-momae#1]
salut,
désolé je ne sais pas comment te contacter via github du coup je créé une issue mais je la supprimerais après !
j'étais à la recherche de ton repo avec le sso azure dont tu parle sur les forums GLPI, est-ce qu'il est privé ?
merci pour ton aide !
Simon

**Comment by virtazp** [comment]
Salut,
J'avais supprimé les sources.
J'ai remis les sources. Ce n'est pas un plugin que j'ai créé. Je l'ai modifié pour avoir la possibilité d'ajouter des utilisateurs à la volée. C'est à dire que leurs comptes se créent à leur première connexion SSO.

Si tu as des questions, hésite pas à me les poser dans le bon repository.
